### PR TITLE
Add tab bar support

### PR DESCRIPTION
**Pull request by steve228uk**
Hello again!

This pull request adds tab bar support to TVMLKitchen. It's not quite finished but I wanted to get your opinion before I tidy it up.

I've created a shared instance of a new object called `KitchenTabBar`. This tab bar has an `items` property that accepts a number of `TabItem` instances. Each `TabItem` features a `title` and a `handler` with the handler being called every time the tab changes.

Here's how you would setup a TVMLKitchen app to use a tab bar:

```
func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {

    Kitchen.prepare(launchOptions, evaluateAppJavaScriptInContext: nil, actionIDHandler: actionIDHandler, playActionIDHandler: playActionIDHandler)

    KitchenTabBar.sharedBar.items = [
        HomeTab(),
        SettingsTab()
    ]

    return true
}
```

And here is what your `HomeTab` struct would look like:

```
struct HomeTab: TabItem {

    let title = "Home"

    func handler() {
        print("Called whenever the tab changes")
        Kitchen.serve(urlString: "https://raw.githubusercontent.com/toshi0383/TVMLKitchen/master/SampleRecipe/Catalog.xml.js", type: .Tab)
    }

}
```

The new `.Tab` presentation type is only to be used whenever a user wishes to keep a view within a tab. It uses a new JS presenter that has been adapted from some of Apple's sample code.

```
function menuBarItemPresenter(xml) {
    var feature = currentTab.parentNode.getFeature("MenuBarDocument");
    if (feature) {
        var currentDoc = feature.getDocument(currentTab);
        if (!currentDoc) {
            feature.setDocument(xml, currentTab);
        }
    }
}
```

simulator screen shot 15 mar 2016 22 08 42

### CODE REVIEW

**Comment by toshi0383** [comment]
Awesome! I love this idea.😍

**Comment by steve228uk** [comment]
@toshi0383 Yay! Glad you like it 😊 I'll clean it up and get it ready for merge today.

**Comment by steve228uk** [comment]
This has been tided up and documented correctly now. Just going to do some additional testing in a project I'm working on before it's good to merge.

**Comment by toshi0383** [comment]
It would be great if we could present a native UIViewController as an item of TVML MenuBar, but I don't think it's possible. There seems to be no access to the UITabBarController instance.

**Comment by steve228uk** [comment]
@toshi0383 I can have a look and see if I can find something. I did try a native `UITabController` and serving TVML but the TVML just replaced the tab controller on the stack so that didn't work.

It's gotta be possible somehow :smile:

**Comment by toshi0383** [comment]
> I did try a native UITabController and serving TVML but the TVML just replaced the tab controller on the stack so that didn't work.

Yea I've got the same thing. I could find a instance of [this class](https://github.com/neonichu/tvOS-headers/blob/master/TVMLKit/_TVAppNavigationController.h) using `po [[UIWindow keyWindow] recursiveDescription]` in lldb, but we should not use this otherwise app would be rejected by apple.

**Comment by steve228uk** [comment]
@toshi0383 Unfortunately it looks like this is all private (https://github.com/neonichu/tvOS-headers/blob/master/TVMLKit/_TVMenuBarController.h)

I think the dev needs to make the decision whether they use Storyboard tabs or TVML tabs. I am going to look and see if we can get TVMLKitchen views to show inside storyboard tabs in a future PR.

**Comment by steve228uk** [comment]
@toshi0383 This should be good to merge now if you're happy with it. I'm gonna add the loading bits mentioned in #36 into another PR.

**Comment by toshi0383** [comment]
LGTM👍🚀🛳🚢

**Pull request merged**
