### PR TITLE
Deprecate sharedBar

### PR DESCRIPTION
**Pull request by toshi0383**
As of #69, we should deprecate the sharedBar singleton instance.

### CODE REVIEW

**Comment by toshi0383** [comment]
@steve228uk Any thoughts on this ?

**Comment by steve228uk** [comment]
@toshi0383 As long as it can be served as a root view for the app again I think this is a good idea. How are you handling actions now there are multiple tab bars?

**Comment by steve228uk** [comment]
Just seen #73, this makes a lot of sense

**Comment by toshi0383** [comment]
Great!😄
Merging this.

**Pull request merged**
