### PR TITLE
KitchenTabBar: Mark init() public

### PR DESCRIPTION
**Pull request by anthonycastelli**
Mark init() public to allow presenting the tabor modaly.

### CODE REVIEW

**Comment by anthonycastelli** [comment]
Is the Default presentation type `.Modal`? With my little digging it's not, more of like a push?

**Comment by toshi0383** [comment]
Thanks!!

Can you please explain why it should be presented modally by default ?

**Comment by anthonycastelli** [comment]
I'm still digging through the framework and learning more about it, but `.Default` seems to be a replace instead of a push. My goal with being able to present a TabBar from a button is to allow me to go back to that screen that presented the TabBar. Unless my understanding of `.Default` is wrong and it just adds a layer to the View Stack, `.Modal` wouldn't be required.

**Comment by toshi0383** [comment]
Merging this to address #68 anyway. 🚢

I will take a look about default presentation behavior. Looks like it is more general behavior issue than TabBar specific behavior.

**Pull request merged**
