### PR TITLE
Add Alert Recipe

### PR DESCRIPTION
**Pull request by steve228uk**
Hello!

This pull request adds an alert recipe as well as the ability to dismiss modals. Buttons are entirely optional.

``` swift
let buttons = [
    AlertButton(title: "OK", actionID: "alertAction"),
    AlertButton(title: "Cancel"),
]
let recipe = AlertRecipe(title: "Alert View", description: "A short description of what the alert does can go here.", buttons: buttons)
Kitchen.serve(recipe: recipe)
```

``` swift
Kitchen.dismissModal()
```

simulator screen shot 15 mar 2016 09 38 59

### CODE REVIEW

**Comment by steve228uk** [comment]
Also added the descriptive alert recipe which works identically.

simulator screen shot 15 mar 2016 10 26 39

**Comment by toshi0383** [comment]
Great!
Could you also update README.md's recipe section and CHANGELOG.md ?

**Comment by steve228uk** [comment]
@toshi0383 Yeah, sure thing! 😊

**Comment by toshi0383** [comment]
Our dog has been soo lazy...
But I found SwiftLint violations as follows.

```
Done linting! Found 13 violations, 1 serious in 11 files.
```

Could you please `brew update && brew install swiftlint` and take care of them ?

**Comment by steve228uk** [comment]
Will do 😊

**Comment by steve228uk** [comment]
@toshi0383 Swiftlint violations fixed. Should be good to merge :fork_and_knife:

**Comment by toshi0383** [comment]
Thank you ! Let's merge this.🍔

**Pull request merged**
